# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created: Sun Oct 16 23:29:25 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 440)
        font = QtGui.QFont()
        font.setFamily("ori1Uni")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 581, 431))
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 561, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -242, 547, 776))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setLineWidth(2)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.calc_pushButton = QtWidgets.QPushButton(self.tab)
        self.calc_pushButton.setGeometry(QtCore.QRect(200, 350, 161, 41))
        self.calc_pushButton.setObjectName("calc_pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 20, 401, 327))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.c_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c_label.setObjectName("c_label")
        self.gridLayout_2.addWidget(self.c_label, 8, 0, 1, 1)
        self.tp_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tp_label.setObjectName("tp_label")
        self.gridLayout_2.addWidget(self.tp_label, 5, 0, 1, 1)
        self.k1_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.k1_lineEdit.setObjectName("k1_lineEdit")
        self.gridLayout_2.addWidget(self.k1_lineEdit, 1, 3, 1, 1)
        self.tpr_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tpr_label.setObjectName("tpr_label")
        self.gridLayout_2.addWidget(self.tpr_label, 9, 0, 1, 1)
        self.c_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.c_lineEdit.setObjectName("c_lineEdit")
        self.gridLayout_2.addWidget(self.c_lineEdit, 8, 1, 1, 1)
        self.tk2_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tk2_label.setObjectName("tk2_label")
        self.gridLayout_2.addWidget(self.tk2_label, 7, 0, 1, 1)
        self.tk1_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tk1_lineEdit.setObjectName("tk1_lineEdit")
        self.gridLayout_2.addWidget(self.tk1_lineEdit, 6, 1, 1, 1)
        self.tk1_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tk1_label.setObjectName("tk1_label")
        self.gridLayout_2.addWidget(self.tk1_label, 6, 0, 1, 1)
        self.tp_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tp_lineEdit.setObjectName("tp_lineEdit")
        self.gridLayout_2.addWidget(self.tp_lineEdit, 5, 1, 1, 1)
        self.k2_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.k2_lineEdit.setObjectName("k2_lineEdit")
        self.gridLayout_2.addWidget(self.k2_lineEdit, 2, 3, 1, 1)
        self.m_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m_label.setObjectName("m_label")
        self.gridLayout_2.addWidget(self.m_label, 10, 0, 1, 1)
        self.n_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.n_label.setObjectName("n_label")
        self.gridLayout_2.addWidget(self.n_label, 1, 0, 1, 1)
        self.to_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.to_label.setObjectName("to_label")
        self.gridLayout_2.addWidget(self.to_label, 2, 0, 1, 1)
        self.to_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.to_lineEdit.setObjectName("to_lineEdit")
        self.gridLayout_2.addWidget(self.to_lineEdit, 2, 1, 1, 1)
        self.k1_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.k1_label.setObjectName("k1_label")
        self.gridLayout_2.addWidget(self.k1_label, 1, 2, 1, 1)
        self.n_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.n_lineEdit.setObjectName("n_lineEdit")
        self.gridLayout_2.addWidget(self.n_lineEdit, 1, 1, 1, 1)
        self.m_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.m_lineEdit.setObjectName("m_lineEdit")
        self.gridLayout_2.addWidget(self.m_lineEdit, 10, 1, 1, 1)
        self.tk2_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tk2_lineEdit.setObjectName("tk2_lineEdit")
        self.gridLayout_2.addWidget(self.tk2_lineEdit, 7, 1, 1, 1)
        self.tdi_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.tdi_label.setObjectName("tdi_label")
        self.gridLayout_2.addWidget(self.tdi_label, 11, 0, 1, 1)
        self.tdi_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tdi_lineEdit.setObjectName("tdi_lineEdit")
        self.gridLayout_2.addWidget(self.tdi_lineEdit, 11, 1, 1, 1)
        self.p_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.p_label.setObjectName("p_label")
        self.gridLayout_2.addWidget(self.p_label, 12, 0, 1, 1)
        self.p_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.p_lineEdit.setObjectName("p_lineEdit")
        self.gridLayout_2.addWidget(self.p_lineEdit, 12, 1, 1, 1)
        self.tpr_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tpr_lineEdit.setObjectName("tpr_lineEdit")
        self.gridLayout_2.addWidget(self.tpr_lineEdit, 9, 1, 1, 1)
        self.delta_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.delta_label.setObjectName("delta_label")
        self.gridLayout_2.addWidget(self.delta_label, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 2, 1, 1)
        self.delta_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.delta_lineEdit.setObjectName("delta_lineEdit")
        self.gridLayout_2.addWidget(self.delta_lineEdit, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 531, 271))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аналитическая модель"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Аналитическая модель<br/><br/>1. Во вкладке &quot;<span style=\" font-weight:600;\">Ввод параметров</span>&quot; заполнить форму ввода значениями параметров. Значения входных параметров приведены ниже.</p><p>2. Нажать на кнопку &quot;<span style=\" font-weight:600;\">Произвести расчет</span>&quot;. При корректном вводе откроется вкладка с результатами вычислений.</p><p><span style=\" font-weight:600;\">Входные значения:</span></p><p><span style=\" font-weight:600;\">N</span> - количество рабочих станций</p><p><span style=\" font-weight:600;\">T</span><span style=\" font-weight:600; vertical-align:sub;\">o</span> - среднее значение времени дообработки на рабочей станции сети запроса от этой станции к базе данных на сервере</p><p><span style=\" font-weight:600;\">T</span><span style=\" font-weight:600; vertical-align:sub;\">P</span> - среднее значение времени формирования запроса от рабочей станции сети к базе данных на сервере</p><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">K1</span> - среднее значение времени передачи запроса по каналу (прямое направление)</p><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">K2</span> - среднее значение времени передачи запроса по каналу (обратное направление)</p><p><span style=\" font-weight:600;\">C</span> - число процессоров сервера</p><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">пр </span>- среднее значение времени обработки запроса в ЦП сервера</p><p><span style=\" font-weight:600;\">m</span> - количество дисков</p><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">дi</span> - среднее значение времени обработки запроса в диске сервера</p><p><span style=\" font-weight:600;\">Р</span> - вероятность обращения запроса к ЦП после обработки на диске</p><p><br/></p><p><span style=\" font-weight:600;\">K</span><span style=\" font-weight:600; vertical-align:sub;\">1</span> - коэффициниент для определения начального значения интесивности потока (0.9…0.999995)</p><p><span style=\" font-weight:600;\">K</span><span style=\" font-weight:600; vertical-align:sub;\">2</span> - коэффициент для определения шага изменения интенсивности потока (10...100000)</p><p><span style=\" font-weight:600;\">Δ</span> - отношение разницы интесивностей потока до и после итерации к интенсивности после итерации (0.000001...0.9)</p><p><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Описание работы"))
        self.calc_pushButton.setText(_translate("MainWindow", "Произвести расчет"))
        self.c_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">C</span></p></body></html>"))
        self.tp_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">T</span><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">P</span></p></body></html>"))
        self.k1_lineEdit.setText(_translate("MainWindow", "0.995"))
        self.tpr_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">ПР</span></p></body></html>"))
        self.c_lineEdit.setText(_translate("MainWindow", "1"))
        self.tk2_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">K2</span></p></body></html>"))
        self.tk1_lineEdit.setText(_translate("MainWindow", "1"))
        self.tk1_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">K1</span></p></body></html>"))
        self.tp_lineEdit.setText(_translate("MainWindow", "100"))
        self.k2_lineEdit.setText(_translate("MainWindow", "100"))
        self.m_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m</span></p></body></html>"))
        self.n_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Число ремонтиков</p></body></html>"))
        self.n_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N</span></p></body></html>"))
        self.to_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">T</span><span style=\" font-weight:600; vertical-align:sub;\">o</span></p></body></html>"))
        self.to_lineEdit.setText(_translate("MainWindow", "0"))
        self.k1_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">К</span><span style=\" font-weight:600; vertical-align:sub;\">1</span></p></body></html>"))
        self.n_lineEdit.setText(_translate("MainWindow", "10"))
        self.m_lineEdit.setText(_translate("MainWindow", "1"))
        self.tk2_lineEdit.setText(_translate("MainWindow", "1"))
        self.tdi_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">Дi</span></p></body></html>"))
        self.tdi_lineEdit.setText(_translate("MainWindow", "10"))
        self.p_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">P</span></p></body></html>"))
        self.p_lineEdit.setText(_translate("MainWindow", "0"))
        self.tpr_lineEdit.setText(_translate("MainWindow", "10"))
        self.delta_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Δ</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">K</span><span style=\" font-weight:600; vertical-align:sub;\">2</span></p></body></html>"))
        self.delta_lineEdit.setText(_translate("MainWindow", "0.05"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ввод параметров"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Загрузка рабочей станции"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Загрузка пользователя"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Среднее кол-во работающих РС"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Загрузка канала"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Загрузка процессора"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Загрузка i-го диска"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Среднее время цикла системы"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Среднее время реакции системы"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "Начальная интенсивность фонового потока"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "Конечная интенсивность фонового потока"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "Количество итераций"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Значение"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Результаты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

